### ISSUE TITLE
each() hangs when the dictionary is empty

### ISSUE THREAD

**Issue by vaughan99** [wilsaj/metalsmith-each#3]
I submitted a PR for a fix.  Basically the done() function never gets called if there are no files in the dictionary.  This happens for us especially when used in conjunction with watch(), and the file that was changed was not part of the branch() that is using each().

**Comment by wilsaj** [comment]
closed as of d75a8ab

**Comment by wilsaj** [comment]
Thank you for the issue and PR! :+1:
